### ISSUE TITLE
Could not save Rigid transforms

### ISSUE THREAD

**Issue by bpavie** [trakem2/register_virtual_stack_slices#3]
Hi 
I tried to save the transforms with rigid contrains but the file is not saved. I also tried using the jython script with no result neither.

**Comment by iarganda** [comment]
Hello @bpavie 

Can you tell me step by step what you did? I just run an affine registration with rigid constraints and it worked for me.

**Comment by bpavie** [comment]
I tried to register 2 images using rig transformation by using the jython script described on the plugin page in Scripting / PlugIn with the same parameters.
After the run, the images are correctly registered but the transform file is not saved in the transf_dir directory.

**Comment by iarganda** [comment]
I just tried the script and it works for me. Did you get any error message in the log window? Are you sure the path to the transformation directory is right?

**Comment by bpavie** [comment]
Yes, the path is correct. I will try with a more up-to-date Fiji, and will let you know.

**Comment by iarganda** [comment]
OK, please, let me know if find a solution.

**Comment by bpavie** [comment]
It looks to work with the last version, sorry for the noise and thanks again for this plugin! I couldn't reproduce the bug on my Fiji version.

**Comment by iarganda** [comment]
I'm glad to hear that!
